apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-granana
  namespace: ns-granana
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - granana.techlearning.me
      secretName: granana-tls
  rules:
    - host: granana.techlearning.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: granana
                port:
                  number: 80